trigger: none

stages:
- stage: build
  displayName: build stage
  jobs:
  - template: 'build_job_temp.yaml'
    parameters:
      solutionpath: 'dotnet/demoapp.csproj'
      artifactname: 'test'

- stage: dev_deploy
  displayName: dev deployment
  dependsOn: build
  jobs:
  - job: dev_deploy
    displayName: dev deployment
    steps:
    - template: 'deploy_steps.yaml'
      parameters:
        environment: 'dev'

- stage: qa_deploy
  displayName: qa deployment
  dependsOn: build
  jobs:
  - job: qa_deploy
    displayName: qa deployment
    steps:
    - template: 'deploy_steps.yaml'
      parameters:
        environment: 'qa'

- stage: uat_deploy
  displayName: uat deployment
  dependsOn: 
   - dev_deploy
   - qa_deploy
  jobs:
  - job: uat_deploy
    displayName: uat deployment
    steps:
    - template: 'deploy_steps.yaml'
      parameters:
        environment: 'uat'